### ISSUE TITLE
Problem: captcha unreusable

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1000]
Problem:  the current global helper has domain specific logic in main.js, and opens a modal of it's own, I think, since placing {{{captcha}}} doesn't do anything. Uncommented, too.

**Comment by janat08** [comment]
@gazhayes

**Comment by gazhayes** [comment]
ping @AshHimself and @anbud

**Comment by gazhayes** [comment]
> Uncommented, too.

Grrrrrrrrr.

**Comment by anbud** [comment]
I wrote most of the captcha logic (before the modal) and it was modular before (including {{{captcha}}} on a page was supposed to display it). I guess the solution here is to copy the modal code from `/currency/x` page to the helper in order to make it work site-wide. Domain specific logic can be moved to the page that's using the helper.

Also, you can see an example of how to use the server side part of the captcha verification [here](https://github.com/Blockrazor/blockrazor/blob/master/imports/api/redflags/methods.js#L39-L72), `checkCaptcha` is a modular function that accepts the captcha code returned from recaptcha, a [future object](http://www.discovermeteor.com/patterns/5828399), and client's IP addess.

**Comment by janat08** [comment]
I'm not inclined to doing this even if I created the issue. I objected to modal being shown, as it would be best to create the modal template instead. I imagine @AshHimself should look at decoupling the logic he introduced or complain about how it originally looked for @andbud to introduce the changes.

**Comment by chamidu-supeshala** [comment]
Hi @janat08 , @anbud  , @gazhayes  It's me who implemented a modal to display recaptcha.  You can see my commit here:  #921

Even before making any changes to that helper, I think that global helper already was **dedicated** to avoid spamming activity, and it **only** rendered a captcha, only if two consecutive user activities fired within 10 seconds. (it is clearly commented in the code)

`if ((user && user.activity.length > 1 && (user.activity[0].time - user.activity[1].time < 10000))) { 
        // needs captcha if he's posting too fast (10 seconds between)
        Meteor.setTimeout(() => window.captcha = grecaptcha.render($('.g-recaptcha')[0]), 800)
        return 'Please complete the captcha before continue<br/><form id="js-cap">${cap.get()}</form>'
}else{
        return ''
}`

Therefore even before i implemented the modal, that global captcha helper was bonded with a domain specific logic, which is to detect and render captcha intermediately when spam activity detected.  And after implementing the modal, i wanted to automatically close the modal after successful verification, so i had to attach a callback function in the global helper itself, all because that the domain specific logic was already presented in that global helper. It is the only change i made to that global helper.

What @janat08 's  problem is that 'global recaptcha opens a modal of it's own'. Yes, that is because this global captcha helper is already bonded to a specific domain which is to **auto render a captcha where ever any spamming activity detected**  

So it is not suitable for the #995 problem, where the purpose is totally different.
(purpose is to check whether the person who fills the subscription form is a robot, so we need to **manually render a captcha** in all subscription forms)

That is all my understanding and my apologies if i have anything misunderstood. For solving this issue, my suggestions are as follows:

1. Making the global helper, purely global by moving domain specific code (spam activity detection code) to another local helper.  However there is another issue with this move, as we may need to use that _auto spamming detection captcha_  more than in a single template. So perfect solution would be make it a reusable component. (Dunno whether it is possible, though)

2. Another solution would be move the modal code from /currency/x page to the global helper and register this specific reusable captcha with a name something like 'botSpamDetectionCaptcha' rather just 'captcha'. This is what @anbud suggested. Yes this would be nicer, as we can use this helper anywhere is the code to auto detect spam messages.  If we go with this solution, the captcha requirement for #995 can be seen as a too specific thing, where we can manually render a captcha for that specific purpose in the local helper itself. (using grecaptcha.render() method)
