### ISSUE TITLE
problem: no client side tests

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1001]
Problem: as demonstrated by #996 we need client side tests so that contributors can add tests to features they work hard to create, otherwise other contributors can sometimes break them and it can take a while to find out.

As far as I can see, the question we need answered before being able to solve this is: what is the simplest possible way to do client CI testing?

**Comment by gazhayes** [comment]
OK, yeah I don't see anything wrong there. Do you feel like setting it up?

**Comment by anbud** [comment]
Sure thing. I'll include an example PR how to write client tests using webdriver as well.

**Comment by anbud** [comment]
Done in #1002. 
A small example test is in `/imports/ui/returnedCurrencies/homepage.ui-test.js`. Please note that all UI tests files from now on should be placed somewhere in the `/imports` directory and end with the extension `.ui-test.js` in order to be recognized by the WebDriverIO. The syntax used for writing tests is quite similar to Mocha, and I've linked to the full browser API in the example test file.

**Comment by janat08** [comment]
Jest all the way =.=

**Comment by gazhayes** [comment]
> Jest all the way =.=

I don't actually see any problem in using Jest in addition to this, the problem it would be solving is that contributors who are used to Jest are more likely to write tests if its there.

@anbud do you see any problems?

**Comment by anbud** [comment]
@gazhayes, nope, I don't see any problems, we can run both webdriver and jest tests. 
I'll also implement a way to run jest tests in CI as well as a part of this issue then.

**Comment by anbud** [comment]
Done in #1022.
