### ISSUE TITLE
Problem: no client side tests have been written

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1035]
Problem: there are not currently any client side tests. We now have a couple of test frameworks installed and CI'd (see #1001), so there's no excuse not to use them. 

Solution: If you write any server side code, and you don't want it to break later, write a test for it. If you write client side code and you don't want it to break later, write a client side test. 

If you solve an issue and someone else breaks it and doesn't know, it's not their fault, **it's your fault** for not writing a test.

Pull requests that don't have tests included should now be a rare thing. 

If you've written code in the past that you don't want to be broken by someone, you should go back and write a test now.

ping @janat08 @AshHimself @samuelralak @anbud @MadanBhandari @chamidu-supeshala

**Comment by samuelralak** [comment]
roger that chief 👍

**Comment by anbud** [comment]
Agreed, let the testing begin! :)

**Comment by janat08** [comment]
"scripts": {
    "start": "meteor run",
    "debug": "meteor run --inspect",
    "lint": "./node_modules/.bin/eslint . --fix",
    "test": "jest --testMatch '**/?(*.)(jest-test).js?(x)'"
  },
I tried adding test script, and it doesn't like regex I placed.

**Comment by anbud** [comment]
@janat08, This seems to work: `"test": "jest --testMatch \"**/?(*.)(jest-test).js?(x)\" --passWithNoTests"`

**Comment by janat08** [comment]
@blockrazorbot unclaim, since it won't allow multiple claims

**Comment by gazhayes** [comment]
You don't really need to claim this one anyway. It's a reminder for everyone.

**Comment by janat08** [comment]
@anbud ?

**Comment by anbud** [comment]
@janat08, sorry, I've completely missed this one. I'll look into it and get back to you here.

**Comment by anbud** [comment]
@janat08, I believe the easiest way here would be to test it out on a template that already uses it (e.g. `/compareCurrencies`) using webdriver + mocha client tests. You can use [WD API](http://webdriver.io/api.html) to simulate data input and to check whether everything is working correctly (e.g. popup is populated with right data, events are handled properly, etc).

If you want, I can write an example test for you for this one, maybe it would be easier that way. :)

**Comment by anbud** [comment]
## Running WDIO tests locally
In order to successfully run WDIO + Mocha tests locally, you'll have to follow the following steps:

### Installing and running selenium-standalone
- npm install selenium-standalone@latest -g
- selenium-standalone install
- selenium-standalone start &

(*Please note that first two commands only have to be run once, the first time*)

### Installing WDIO + Mocha
- npm install -g wdio-mocha-framework webdriverio assert

### Running WDIO tests
- wdio wdio.conf.js 

(*Please note that this command has to be run from the project directory*)

### Possible problems
- ERROR: unknown error: no chrome binary at /usr/bin/google-chrome-stable

If this error ocurrs, please update `wdio.conf.js` to use the correct path to `chrome` binary. 
Changing the path to `chrome` binary requires editing line 9 of `wdio.conf.js` (`binary: '/usr/bin/google-chrome-stable'`).
For example, to get it running on Windows, you'll probably have to change it to: 
`binary: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'`.
Please don't commit your modified `wdio.conf.js` as it'll break Travis CI build cycle.
If you don't have Chrome installed, you'll have to install it first. The latest version works correctly in headless mode without modifications.

- All tests are failing

If you experience this error, please make sure that the Meteor instance is running, as WDIO doesn't report that the host is down, it just fails tests.

### Example output
If everything goes correctly, when running the tests, you'll currently get something like this:
```

..

2 passing (15.10s)
```


@gazhayes, @janat08, here's documentation on how to run WDIO + Mocha tests locally. It should probably be included in the README.

**Comment by gazhayes** [comment]
> It's suppose to use/check default location of chrome installation by default unless you specify elsewhere.

The default location is different on every operating system.

**Comment by janat08** [comment]
I set browser.pause to 10000, but then I can't use jquery methods or access globals it seems.
