### ISSUE TITLE
problem: all menu items are visible when not logged in

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#107]
Problem: all menu items are visible when not logged in.

Solution: hide all menu items until the user is authenticated.

**Comment by AshHimself** [comment]
@gazhayes - Can you please advise should menu items should be visible when a user is not authenticated?

**Comment by gazhayes** [comment]
In addition to this, some menu items should also be hidden from normal users and only be visible to moderators. There will probably be a need for an admin level too.

What's probably more important is how you impliment showing and hiding for different types of users so that it's simple to add a new menu item and have it shown to the correct type of user.

I haven't thought specifically about what should be shown to who, but I think it's mostly self explanatory (or at least logical), if you think it should be hidden it probably should be. Though it's probably a good idea to 'tease' people with things they can't do till they log in or sign up.

**Comment by AshHimself** [comment]
Original menu issue has been resolved but the role issue still exists and issue raised to track #117

**Comment by AshHimself** [comment]
Fixed #118
