### ISSUE TITLE
Problem: entire collection is required to sort by data quality metric

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1089]
Problem: adding quality field during publication will not let mongo perform sort and limit, which doesn't entirely matter if localCollection is used, otherwise it won't work and isn't the best performance. The publication that does it says it intends to sort by that.

**Comment by anbud** [comment]
@janat08, the publication you're talking about, `dataQualityCurrencies`, is used exclusively on the home route, in conjunction with the local collection, so, sorting by quality field works just fine, and limit also works. 

I agree that it wouldn't have the best performance otherwise, but, when I wrote it, I didn't plan on using it anywhere else. I don't really think this needs fixing, it's just a specific publication for a specific route.
