### ISSUE TITLE
problem: no in-your-face encougement to look at bounties page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1100]
Problem: people may not initially be aware there are bounties, and bounties are a critical part of Blockrazor.

Solution: add bounty menu item to the top navigation bar next to logo. Since this will add too much clutter to small screens, top navigation bar menu items should only be displayed on regular screens and *not* mobile devices or small screens.

**Comment by AshHimself** [comment]
What about a tooltip as well. Sorta like when you sign up to gmail it
highlights key features.

**Comment by gazhayes** [comment]
I think a menu item top left next to the logo will be enough, if we start using tooltips like that it adds unnecessary complexity

**Comment by chamidu-supeshala** [comment]
After adding it to the top-navbar, do we need to remove entry from side nav? or keep the sidenav entry also?

**Comment by gazhayes** [comment]
I personally think leaving it is ok

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by chamidu-supeshala** [comment]
@gazhayes currently there is a bounty icon in the top navigation bar for mobile screens. So it will not add additional clutter to small screens, because bounty icon already there for small screens. So i think we don't need to hide those current top navigation menu items from mobile devices, as current icon set fits well in most of the small screens. Do we need to hide them (and move to side nav) for small screens?

**Comment by gazhayes** [comment]
On larger screens it should really say "bounties"

**Comment by chamidu-supeshala** [comment]
fixed in #1104

**Comment by chamidu-supeshala** [comment]
@blockrazorbot remove 'in progress'
@blockrazorbot  label 'done'

**Comment by chamidu-supeshala** [comment]
@blockrazorbot remove 'in progress'

**Comment by chamidu-supeshala** [comment]
@blockrazorbot remove "in progress"

**Comment by chamidu-supeshala** [comment]
@blockrazorbot label "done"
