### ISSUE TITLE
Problem: going to /problems and back to / results in no data being loaded

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1117]
Problem: going to /problems and clicking the log to go back to / results in no data being loaded:

<img width="788" alt="screen shot 2018-04-14 at 6 11 17 pm" src="https://user-images.githubusercontent.com/8143945/38767136-4b8869b6-400f-11e8-88b9-ba2679815e8c.png">

**Comment by anbud** [comment]
@blockrazorbot claim

**Comment by anbud** [comment]
This one is not reproducible on the local server, but I've tried implementing a possible fix in #1119.
Although, I believe this one is connected to #1068 and it depends on solving that one first. It's also not deterministic, as it occurs in about 70% of tries.

Mainly, the bug happens because when you load the `/problems` page, `SubsCache.ready()` returns `false`, and stays `false` when you go to `/` page. But, if you, for example, visit the `/bounties` page after, it becomes `true` and this problem will disappear until you refresh the page. So, the issue is connected with `SubsCache.ready()` returning `false` in some nondeterministic situations.

**Comment by gazhayes** [comment]
> So, the issue is connected with SubsCache.ready() returning false in some nondeterministic situations.

@janat08 any ideas?

**Comment by janat08** [comment]
I couldn't reproduce. This points at localizable collection interacting with subs cache poorly, but removing localizable collection for [/] didn't do anything with subsCache returning false with fast-render blockingDDP which isn't entirely related to the issue.

**Comment by gazhayes** [comment]
Will close it for now, people will probably just refresh the page when it happens, it's not a huge problem and looks like it's going to be painful to fix.

**Comment by janat08** [comment]
Btw I was trying to reproduce on local :P. Maybe check if some global sub is ready and compare it against subsCache.ready() method to then return a message about server error?

**Comment by gazhayes** [comment]
@janat08 it would be good if you can do a little bit more investigating on the production server and see if that reveals any more information,  maybe you'll see something that makes for an easy fix. If you find out what the real problem is, don't be afraid to log it as a new issue :)
