### ISSUE TITLE
Problem [sidebar] moderator dashboard link randomly disappears

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1184]
Problem: the moderator dashboard link randomly disappears from the sidebar and the page has to be refreshed to bring it back. Probably some reactive subscription taking time to do another check on whether the user is a moderator or not, or that in combination with subscache.

Possible solution: if subscache is in use for this one, disable it. If fast render is not in use, enable it.

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
Fixed in #1237
@blockrazorbot label "done"

**Comment by AshHimself** [comment]
@blockrazorbot done

**Comment by gazhayes** [comment]
@janat08 can you explain more with a bit more detail. Why did you have to revert this?

**Comment by janat08** [comment]
#1251

**Comment by janat08** [comment]
discussion in #1196

**Comment by janat08** [comment]
The original pull request wouldn't even stop subscache from deleting it.

**Comment by gazhayes** [comment]
OK. So this problem is a problem again?

**Comment by janat08** [comment]
If the test failed it likely is not, otherwise I didn't at all diagnose the problem aside from finding a culprit. There's an issue for refining for the accuracy of allReady() method of subsCache, and I suggested actually using individual subscription instances instead of allReady in liu of that. If you'd like me to find if the problem that is, is not what manifested itself here, I can go check.

**Comment by janat08** [comment]
btw the test in question will fail on use of Meteor.subscribe, since it also tests genuine subscriptions other than the ones from fast-render.
