### ISSUE TITLE
Problem: Automated code reformatting

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1231]
Problem: In a related issue, a linter was added, rather than basic formatter of code that checks tags and indentations. I beautified one of the method files and I can't merge at all now (although I then went ahead and deleted some unnecessary blank lines).

Possible Solution: use CI linter that was implemented previously, and configure it after the reference files so long as they don't require human intervention.

Possible Solution: There's a service for github that beautifies files as they come in for 50$.

Possible Solution: You can try and use something like [beautify](https://github.com/beautify-web/js-beautify), with this lib specifically unable to beautify repo, but has extensions in every editor and is even likely used by default.

**Comment by gazhayes** [comment]
The simplest way to solve this is not use any beautification. We are absolutely not using it as part of github as this completely breaks the C4 and it also hides code smells.

**Comment by janat08** [comment]
c4:2.3.3: A patch MUST adhere to the code style guidelines of the project if these are defined.
Unlike what you previously said.

**Comment by janat08** [comment]
Our code style is a little to elaborate too, reallly faithfully comply with it. The reasoning it C4 goes as:
``This is just sanity. I've spent time cleaning up other peoples' patches because they insisted on putting the else beside the if instead of just below as Nature intended. Consistent code is healthier.``

**Comment by gazhayes** [comment]
> Our code style is a little to elaborate too, to reallly faithfully comply with it. 

You are absolutely correct. I put that there temporarily as a reference but this is definitely not a C4ish style guide, it should be like 2-3 paragraphs of basic things that are easy to remember (mostly just indentation etc).

> c4:2.3.3: A patch MUST adhere to the code style guidelines of the project if these are defined.
Unlike what you previously said. I take it this means our codebase isn't supposed to be a mess of formats.

The intention behind that is to get people to follow the guidelines (and see who can't be bothered, because their code might need a closer look). It's _very_ important not to take anything out of control of the contributor, that's why it can't be done automatically on the Github side. If individual contributors want to use lints and reformatters that's fine, and it's ok to define some example ones, but usage has to remain up to the individual contributor.

That's actually why c4:2.3.3 exists in the first place - if we could just take it out of the contributor's control and do it automatically then c4:2.3.3 would not exist.

**Comment by gazhayes** [comment]
@janat08 I have created #1232

**Comment by janat08** [comment]
But then we're reformatting the project? I see no problem with taking something off contributors hands that they will have to do otherwise. VS Code uses beautifier internally but will not accept custom settings, so I'm switching editors and configuring that then or using an external tool for basic editor feature.

**Comment by janat08** [comment]
A lot of reference rules have lint option mentioned, and so we can have like really robust consistency.

**Comment by gazhayes** [comment]
> But then we're reformatting the project?

No. We don't reformat the codebase just for the sake of having a nice looking codebase.

> I see no problem with taking something off contributors hand that they must do otherwise.

That's only because you haven't absorbed the philosophy behind the C4 yet. Though I am happy that you are paying attention to the protocol itself.

It's good for you to make sure that your own pull requests look as nice as possible. Though not as important (for example) as making sure your code contains comments to make it really easy to follow.

**Comment by janat08** [comment]
Moreover it falls in line with goals of C4:
``1. To maximize the scale and diversity of the community around a project, by reducing the friction for new Contributors and creating a scaled participation model with strong positive feedbacks;``
``5. To reduce the internal complexity of project repositories, thus making it easier for Contributors to participate and reducing the scope for error;``

**Comment by gazhayes** [comment]
It has to be in the same commit, there can be no extra commit to do styling issues. Apart from this, any auto styling cannot change too much or it hides code smells. 

We could also probably automatically add "problem" to all patches, but this would not satisfy the reasons behind using a problem statement. Following the style guide is the same thing.

**Comment by janat08** [comment]
Right, so the issue is with CI making another commit. Can it merge them thereafter only keeping patch comments from the 1st one?

**Comment by gazhayes** [comment]
There are numerous issues, but that is one of them. Another major one is not destroying code smell. And another one is contributor autonomy.

**Comment by janat08** [comment]
I imagine if it doesn't require human intervention, that it doesn't affect the semantics of code.

**Comment by sjmackenzie** [comment]
No need for code formatters, code smell is a great way to catch bad actors. Develop a styleguide everyone is happy with. #1232 is the root cause of this problem, therefore this issue can be closed.

**Comment by sjmackenzie** [comment]
A more clear explanation: bad programmers and bad actors cause problems, this messes with people, and code. Bad actors code is generally chaotic, badly formatted and doesn't adhere to the code style of a code base. In other words they couldn't give a damn as their primary goal is to cause trouble nitpicking here and there, and rebelling against the rules. Rules which are in place to keep harmony in the community. The fastest way to see a bad actor is by looking at shitty code. Code formatters immediately hide that. It also potentially adds opportunity for conflicts in code.

**Comment by sjmackenzie** [comment]
It's better to make a separate commit to style up badly formatted code, it's in the history the bad actor put it there, it doesn't have to hang around forever. When git bisecting or tracking down a problem introduced into the history the programmer can easily skip over `"Problem: code not formatted properly"` as it's highly unlikely the problem was intorduced there. If you conflate styling and actual problem code the diff can become huge and increases code/problem finding time.

**Comment by janat08** [comment]
That is to say that reformatting code is good?

**Comment by gazhayes** [comment]
> That is to say that reformatting code is good?

It *can* be good, when used in the right situation and for the right reasons (and within the right scope). But it's not *always* good.
