### ISSUE TITLE
Problem: [/addcoin] End user might be demotivated to fill a huge form

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1280]
Problem: Nowadays there are very less instances where we will be given with a huge form to fill out, because it may make a negative impact in user's mind, as no body wants to fill such a long form. 

Solution: My suggestion is to divide the form in to steps, with some friendly headings in each step. (and steps can be designed as cards)

![screenshot from 2018-04-23 20-56-19](https://user-images.githubusercontent.com/27463355/39137936-72d0ee2e-473c-11e8-8774-439424a12722.png)

The above screenshot is from a project i worked, however in that, the steps are designed more in a fancy manner. But in blockrazor, we can make steps more professional. This issue is open for discussion, and welcome everyone's opinion whether this is appropriate or not for addcoin form.

**Comment by anbud** [comment]
I agree, we have to do something about the form, it can get quite big with some options. I get annoyed with it when I have to fill it out for testing purposes. :)

In my opinion, a step-based approach seems sufficient, we just have to decide how to divide it optimally, to achieve equilibrium between the number of steps and the amount of data each step requires.

**Comment by gazhayes** [comment]
Completely agree and have been thinking the same thing for a while. I'll propose a possible solution in the next few hours in terms of how to break it up.

**Comment by AshHimself** [comment]
https://github.com/techlab/SmartWizard looks fairly maintained and has bootstrap 4 support. One challenge will be validating attributes which are visible on that tab. You should not be able to get to the end of the form and have to go back and fix fields. Depending on the urgent I can take this on.

**Comment by gazhayes** [comment]
>  One challenge will be validating attributes which are visible on that tab.

Each page of the wizard could be saved to the db (and validated) independently, there's a flag to set before it shows up on the approval page anyway so it won't impact that.

Added bonus with that is users could 'resume' if not being able to do so is a problem.

**Comment by AshHimself** [comment]
@gazhayes I got ample time today/tomorrow to get started on it.

**Comment by gazhayes** [comment]
OK, I think I've worked this out.

It's probably easier to create a new route for this and keep the existing one as a reference till the new one works properly.
<hr />

Wizard 1:
---------

**[Currency Name] [Symbol]**(min 3 max 5) 
Verify both name and symbol are unique across pending and existing currencies.

_Has this blockchain or currency already launched?_
**[YES, {{name}} has already launched] [NO, {{name}} is new and has not launched yet]**

_Was this created as a fork of an existing blockchain, or was it launched with a new genesis block?_
**[{{name}} is a fork of something else] [{{name}} started with a new genesis block]**

(if FORK):
_Which blockchain was {{name}} forked from?_
**[typeahead of existing currencies]**

_Were funds raised or tokens pre-sold prior to the launch of this blockchain project? Was this an ICO?_
**[NO TOKENS WERE PRE-SOLD]
[SOME TOKENS WERE PRE-SOLD]**

The tense of all the above text should change based on whether or not the coin has launched or not.
---------

The rest can basically follow as it currently works on the existing form but broken up into relevant pages or whatever.

There are some differences though:
There's now the possibility of selecting any existing coin as the parent blockchain. If this is the case, the genesis block timestamp should be taken straight from the parent currency and the user doesn't need to be asked. They do however need to be asked what date the *fork* happened on (when the chain split in two).

If this is or was an ICO: an independent ICO page should be added to collect relevant details, I'll add the details later in a new issue once this issue is closed, but basically the ability to add funding rounds etc.

**Comment by janat08** [comment]
You can validate with a schema for a basic object too, picking out fields that have been done so far at each step.

**Comment by AshHimself** [comment]
Ok i'll tackle this beast! 
@blockrazorbot claim

**Comment by gazhayes** [comment]
Don't try and get it perfect as things will probably be changed around, a first pass is good enough.

**Comment by AshHimself** [comment]
10-4

Being this is on a seperate route i'll keep it agile and push it over when
the UI looks good then worry about the rest once we are happy if that works
for you.

**Comment by AshHimself** [comment]
@gazhayes - so I got a wizard up and running but this validation per form thing is going to be a real pain in the arse as the validation in most wizard plugins I found were all custom. I'll look into what @janat08 said about picking the fields we require per step as that should be a little bit easier.

**Comment by gazhayes** [comment]
You could just send a PR with the wizard itself first and validation can be a separate issue that @janat08 can take a look at.

**Comment by gazhayes** [comment]
Have you got the wizard steps to populate based on previous answers?

**Comment by AshHimself** [comment]
@gazhayes - First revision sent through. Few things to note
- Access via addcoin2
- Commented the code SmartWizard
- I got validation working but it'll need a bit of jquery love to highlight the tab the errors are actually on.
- Any suggested changes so far? Like you said this could be done easier with simpleSchema so thoughts @janat08 ?

**Comment by gazhayes** [comment]
Just tested it. Closing this issue as the original issue is solved, I'll create a new one for validation.

**Comment by gazhayes** [comment]
Actually, may as well make this the /addcoin route now and move the old one to addcoin-legacy for reference only. Then this issue can be closed.

**Comment by AshHimself** [comment]
Sorry mate totally missed this comment and was away for weekend.. doing now.

**Comment by AshHimself** [comment]
@blockrazorbot label 'done'

**Comment by AshHimself** [comment]
@blockrazorbot done

**Comment by AshHimself** [comment]
Fixed in #1374
