### ISSUE TITLE
Problem: can't create exchange at [/addcoin]

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1454]
Problem: create exchange at addcoin does nothing, and it won't show up on list, or show up list of to be added exchanges. the display logic was messed with at #1392. Although it's likely that the create prop to typeahead template doesn't intends for creation to simultaenously create and add exchange, yet doesn't actually add it.

**Comment by anbud** [comment]
Since #1457 is closed, I'll take a look at this. :)

@blockrazorbot claim

**Comment by anbud** [comment]
The issue is fixed in #1507.
@janat08, please review it to check if I unintentionally broke something else, or if it's the best solution here. We have to use a callback (or a promise) for data creation as the data is created asynchronously.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by janat08** [comment]
#1521

**Comment by janat08** [comment]
would you like other issues addressed in issue tracking?

**Comment by anbud** [comment]
As far as I can tell, the core issue here has been fixed, you should open other issues for possible problems, but I believe this one can be closed. :)
