### ISSUE TITLE
problem: [/addCoin] when BTCfork checked genesis date input not visible

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1546]
Problem: if user checked BTCfork checkbox in the STEP1, the genesis timestamp input box not visible in STEP3, and cannot proceed to next step

**Comment by chamidu-supeshala** [comment]
@blockrazorbot claim

**Comment by gazhayes** [comment]
We should be asking for a fork date instead of a genesis date when it's a BTC fork. The genesis block of a BTC fork is simply the Bitcoin genesis block (so it has the same timestamp and we can just pull that from the Bitcoin object in the currencies collection without asking the user). But we still need to know the fork date. It might be better to use a fork block height instead of a fork date actually, since that's the actual empirical data point.

**Comment by chamidu-supeshala** [comment]
> It might be better to use a fork block height instead of a fork date actually

Now i understood the actual problem, its just an unnecessary step validation. because when BTCfork checked, there is fork height (and no any date input). but when proceeding to next step it asked "please input proper date" while there is no date input visible. So the solution will be remove that unnecessary date validation, if BTCfork checked

**Comment by chamidu-supeshala** [comment]
fixed #1548
@blockrazorbot label "done"
@blockrazorbot remove "in progress"
@blockrazorbot done
