### ISSUE TITLE
Problem: [/approvals] No place to approve API bounties

### ISSUE THREAD

**Issue by chamidu-supeshala** [Blockrazor/blockrazor#1615]
Problem:  it seems like the moderator pending API bounty uses an old template, it currently only displays something called `HashrateAPI` bounties only, for the approval. This is how it queried currently:

`Bounties.find({pendingApproval: true, bountyType: "HashrateAPI"})`

But my database has no any bounty with that type. And also not found such bounty in [/bounties] 

Solution: If `HashrateAPI` means a samething as `Hashpower API bounty for a particular currency`, we need to change `/moderatorDash/moderatorPendingAPIBounty` templates to query and display all Hashpower API related bounties for approval. 

otherwise, if separate bounty exists named `HashrateAPI`, and it is accessible from somewhere else in the app, or if you feel like i'm mis-understood something, please close this issue :)

**Comment by anbud** [comment]
As far as I know, `HashrateAPI` is an old type of bounties that's not used anywhere on the site currently. It's not at all compatible with the current system. Hashpower API bounties were created instead of them, but they're automatically approved on first successful API call, so there's no need for moderator actions.

As a solution, you can remove the whole page, it's not used. :)

**Comment by anbud** [comment]
Actually, it's a small job, I'll do it. :)

@blockrazorbot claim

**Comment by anbud** [comment]
Done in #1617.

@blockrazorbot label "done"
@blockrazorbot remove "in progress"
