### ISSUE TITLE
Problem : Not logged-in user's accessibility for project not defined

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#1859]
**Problem : It's not sure what user can do without login**

Solution : Only keep login restriction for adding and editing data, user should be able to see all the information without login.
Here are my points

**Without Login**
- List of currencies
- Search
- Currency details
- Bounties
- Problems

**Login should be requried for**
- Wallet
- Notifications
- Add/Edit currency, bounties, problems etc.

_If there is login required for some reason, I am not sure about that._ 

**Share your ideas on what should and/or should not require login.**

ping @gazhayes @anbud

**Comment by MadanBhandari** [comment]
Currently user can't see list of currencies and search without login, it's compulsory to be logged-in. If this is not on purpose, I will start working on this.

And we also need to change landing page, it should moved to some other path, like in `/about` or move current `/`to another place like `/app` or `/currencies` or something else.

**Comment by anbud** [comment]
If I remember correctly, as Blockrazor is user-driven, it was @gazhayes' idea to hide most of the information from nonregistered users so that users would be compelled to register and, possibly, contribute new data.
But, I don't think that the list of currencies should be hidden from nonregistered users, I think it became hidden after the landing page was introduced. So yeah, landing should probably stay on the `/` route, and we should move the currency list somewhere else so all visitors have access to it.

**Comment by MadanBhandari** [comment]
Currently user can access `/home`, link is on side navigation. I kept Get started link to `/login` as we want user to be logged-in.

**Comment by gazhayes** [comment]
I did this intentionally before, but I guess its better to do it the way Madan suggests at first and then introduce restrictions only after we have a critical mass of users
