### ISSUE TITLE
Problem: currency detail page 'flashes' on load

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#190]
Problem: when going to a currency's detail page, the page 'flashes', especially on slow connections.

**Comment by AshHimself** [comment]
@gazhayes - Not sure if this is the problem here but we really need a global solution to show a loading indicator whilst subscriptions are completing. e.g. editing a currency does the same thing as the DOM loads before the subscription is complete.

**Comment by anbud** [comment]
The problem here was a little bit different, but I generally agree, we do need a loading page. IronRouter has a nice `waitOn` property, but, since we're using FlowRouter, something like [this](https://github.com/kadirahq/flow-router/issues/229#issuecomment-125819349) or [this](https://www.discovermeteor.com/blog/template-level-subscriptions/) should be useful. That would be a simplest possible solution I believe.

**Comment by AshHimself** [comment]
@anbud created #192 to track this.

**Comment by gazhayes** [comment]
Just note that we will probably use fast render for the initial payload so waiting for ddp to crank up shouldn't be much of an issue.
