### ISSUE TITLE
Problem: DOM is displayed before subscriptions are ready

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#192]
Problem: DOM is displayed before subscriptions are ready

Solution: Implementation a progress loader / indicator to indicate that the subscription is still loading and/or DDP transactions are still in progress.

**Comment by gazhayes** [comment]
Another possible solution to this would be to deploy [fast render](https://atmospherejs.com/staringatlights/fast-render)

I used it here but turned it off for some now forgotten reason: 
https://github.com/Blockrazor/blockrazor/blob/ff709fa271babb1363b7b16f6757d402ed66d21b/server/main.js#L147

**Comment by janat08** [comment]
Should this just block main layout, or do you want me to go through lists and stuff?

**Comment by gazhayes** [comment]
Don't block main layout. Especially since we are using fast render wherever possible.

However a loading image while fetching subscriptions would be very good, it has to be on a per template basis though, the UI can load but just show a loading image for parts of the page that require a subscription (often there is more than one element on a page coming from different subscriptions).

**Comment by janat08** [comment]
Reframed in #334, close.
