### ISSUE TITLE
problem: decentralization metric not displayed

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#209]
Problem: the decentralization metric is not displayed on the radar chart. There may be sub-problems associated with this in terms of ELO rankings as well as deciding the best way to incorporate nominal and comparative questions into the dataset.

ping @anbud for opinion.

**Comment by anbud** [comment]
@gazhayes, we can display decentralization data on the radar chart the same way we display the other data, there's no big difference. It's not hard to calculate the spread over the chart.

Currently, the "pseudo" ELO calculation is quite simple (increase/decrease the ELO ranking by 5 if it's a nominal question, and increase/decrease ELO ranking by 2 if it's affected by another comparative question). The only problem could be that decentralization ELO ranking values differ from other ELO rankings. If you want, I could use 400 instead of 0 as a starting value, so the values will be closer.

**Comment by gazhayes** [comment]
Actually, we have to use ELO rankings for decentralization measurements, the current way won't work. I'll add a new issue now.

**Comment by anbud** [comment]
@gazhayes, Since we've switched to the ELO ranking for decentralization in #219, should we display the data here as we display the other data on the radar chart? We could also switch to the new formula for graph data calculation presented in #194.

**Comment by gazhayes** [comment]
Yes to both :)

**Comment by anbud** [comment]
Done in #233.
