### ISSUE TITLE
Problem: errors on hashpower page can be confusing sometimes

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#349]
Problem: when submitting a hashpower data point, if an image isn't uploaded an error is reported "please complete all fields". This also happens when an image is in the process of being uploaded. An indicator (something like what's on the wallet image upload page) would make things less confusing. Making the errors nicer would probably also be good.

**Comment by AshHimself** [comment]
Fixed in #400 

@gazhayes included jquery validation in this package, I believe it would offer a lot of value to add this on other more advanced screens where validation of data is paramount. Just saying DATA REQUIRED in some cases isn't enough and we should possibly help the user on what is required so the data can be more useful and valuable to the community.

**Comment by gazhayes** [comment]
Can you create an issue with a list of places it should be used?
