### ISSUE TITLE
Problem: sidebar menu closes when reloading page

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#350]
Problem: the sidebar closes when refreshing the page (and will also close when changing pages when this is deployed site-wide).

Possible Solution: use a reactive-var or session var

**Comment by AshHimself** [comment]
My suggestion is we go responsive so it auto closes based on screensize and
if you close it yourself it remembers the users choice from view to view.

**Comment by gazhayes** [comment]
Yeah that's probably the best approach.

**Comment by janat08** [comment]
I could take it.

**Comment by gazhayes** [comment]
Ok @janat08, I'll leave this one to you.

**Comment by AshHimself** [comment]
Something like this could do the trick https://codyhouse.co/demo/responsive-sidebar-navigation/index.html#0

**Comment by janat08** [comment]
In theory, I'm done with saving user preference by media breakpoints, and closing sidebar on outside click on mobile. I'm opposed to popovers and usage of nav sidebars other than on mobile.

**Comment by janat08** [comment]
I've set the default for opened sidebar at 991px, and it may glitch on small resizes for unregistered users as it doesn't even try and track their preferences with debounce not being totally reliable at 50ms causing for example sidebar to close on small resolutions when you like open console.

It also doesn't defer saving user preferences since there's not an entirely reliable manner in which it can be done from a quick look. If you'd like I could look into trying and making that work.

**Comment by janat08** [comment]
Also it will close opened sidebar at mobile breakpoint, but it will not block any other events from occuring, so you can't just carelessly click outside sidebar to close it.

**Comment by AshHimself** [comment]
I cant seem to close the sidebar at the moment, there is also hidden menu items at the bottom that I am unable to scroll to.

**Comment by janat08** [comment]
the hidden menu items is a separate issue I had nothing to do with. I imagine it's something you might want to solve with CSS which I'm no good at.
