### ISSUE TITLE
problem: no consistency in client-side validation

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#401]
Problem: no consistency in client-side validation 

Solution: Implement jquery validation on the following routes
- addCoin
- currencyEdit
- profile

Please let me know if I missed any other complex form?

**Comment by janat08** [comment]
methods are supposed to take care of it, theres mdg package for methods that describes how it's done.

**Comment by gazhayes** [comment]
@janat08 can you post a link?

**Comment by AshHimself** [comment]
client side? methods are on the server

**Comment by janat08** [comment]
https://guide.meteor.com/methods.html#validated-method

Run validation code by itself without running the Method body.
Easily override the Method for testing.
Easily call the Method with a custom user ID, especially in tests (as recommended by the Discover Meteor two-tiered methods pattern).
Refer to the Method via JS module rather than a magic string.
Get the Method simulation return value to get IDs of inserted documents.
Avoid calling the server-side Method if the client-side validation failed, so we don’t waste server resources.

**Comment by gazhayes** [comment]
validated-method looks like a pretty good solution here, especially with the integration with simpl-schema.

This is low priority however, but should be kept in mind for new forms.

**Comment by AshHimself** [comment]
Happy to be corrected from someone else but I have used simpl-schema before in the past and any validation errors are done on save to the collection and not easily reported to the UI. Does another package assist to assist in that component? (without switching to auto-form)

**Comment by gazhayes** [comment]
>any validation errors are done on save to the collection

When you use it with collection2 it does that, but you can use it totally independently. I'd say we can probably define schemas separately and import them into server side and client side use of validated-method. This is definitely something to investigate and confirm however, there's no point in using something where code has to be repeated for client *and* server validation.

**Comment by AshHimself** [comment]
I think we can agree to close this now being that we have agreed to use validated-method to do server and client validation as a standard. Please reopen if anyone objects.
