### ISSUE TITLE
Problem : Top Navigation breaking on mobile screen

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#439]
Solution : Change layout on smaller screen, We can use user image instead of User Name to open drop down for My Profile, Edit Profile and Log out ?

**Comment by AshHimself** [comment]
@gazhayes - what is the scope for mobile at this point in time? Are you bothering we responsive design for web or rather invest the time in the actual native mobile app?

**Comment by gazhayes** [comment]
@MadanBhandari 
> can use user image instead of User Name to open drop down for My Profile, Edit Profile and Log out ?   

I don't see any particular reason not to. A fallback image would be needed though in case they don't have a profile picture for some reason. 

@AshHimself 

> what is the scope for mobile at this point in time? Are you bothering we responsive design for web or rather invest the time in the actual native mobile app?   

Basically don't really bother too much. Having the home route work on mobile is probably something that we should do, but anything else is not really important. What is slightly more important is tablets though since everyone seems to be using them now.

**Comment by MadanBhandari** [comment]
Updated on #514

**Comment by MadanBhandari** [comment]
Closed by mistake

**Comment by MadanBhandari** [comment]
This is done, please check and close.

**Comment by gazhayes** [comment]
Nice work @MadanBhandari
