### ISSUE TITLE
Problem : [/currency] currency details page doesn't show enough scope

### ISSUE THREAD

**Issue by MadanBhandari** [Blockrazor/blockrazor#440]
Solution : Update layout, check responsive layout on smaller screens.

@gazhayes 
Please share if you guys have any idea or plans for this.

Related #404 #396

**Comment by gazhayes** [comment]
You see how there are some tab things I put in there? I put those in to show some generic data about what everything means. I don't really think that's the best way to do it though.

There's stuff on that page that won't make a whole lot of sense to people and requires some explanation. Maybe some modals or something next to each bit of information, I don't know.

Also the radar chart, I had a quick look at this before and concluded that it was bloody hard, but it would be cool to have actions (onClick, onHover, or whatever) on each label of the radar chart so that we can put something there to provide users with more data about what everything needs.

Another thing that is related to this isssue is #385

**Comment by gazhayes** [comment]
related: #537

**Comment by MadanBhandari** [comment]
I have some idea about, how it should look.
![currency-details](https://user-images.githubusercontent.com/6429311/37446110-68f225b8-2841-11e8-94a3-055def16c544.png)

First grey area is for chart, and what you say about adding short description or intro of currency ?
ping @gazhayes

**Comment by gazhayes** [comment]
There are already plenty of sites with introductions and statistics, the difference with Blockrazor is that all data is provided by the community (like wikipedia) and always up to date.

So it needs to highlight that fact. Anything in a prime position must be added by users (e.g. features + red flags at the moment). There could be a short summary, limited to x words, contributed by users (and votes would decide which summary makes it to the top). This could basically be the same logic as the features and red flags, but a longer format. You can build that into the UI if you like and myself or someone else will do the backend.

I find tabs etc annoying, I think it's better to have everything on a single page.

For the layout itself, this might be better:

#######################
RADAR CHART



#######################
Distribution graph 
and critical specifications
#######################
SHORT SUMMARY

#######################
FEATURES

#######################
RED FLAGS

#######################
DETAILED SPECIFICATIONS
