### ISSUE TITLE
Problem: LoggerMongo disabled in main.js

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#442]
Problem: server main.js imports are wrong, which I wasn't aware of when I just disabled loggerMongo. The generatebounties and such in imports likely pointed to Bounties.js which is still available.

Solution: Correct imports using utilities.js in imports/api. Enable loggermongo.

**Comment by janat08** [comment]
Unsolved, giving up.

**Comment by anbud** [comment]
@janat08, what's causing issues here?

**Comment by janat08** [comment]
I don't know, it said it has issues with database/Bounties.js on the first line.

**Comment by gazhayes** [comment]
@anbud can you get to the bottom of this one

**Comment by anbud** [comment]
Sure thing, @janat08, give me a little bit more details and I'll assist you. :)

**Comment by janat08** [comment]
``` main.js
// (new LoggerMongo(log, { //TODO: DISABLED FOR NO REASON - other than putting error away in #69
//   collection: AppLogs
// })).enable();
```
This uncommented produces error that's entirely useless.

**Comment by gazhayes** [comment]
Thanks. 

FYI You can do it like this instead of copy/pasting the code, it makes it much easier for us to find the right place in the codebase and track it.

https://github.com/Blockrazor/blockrazor/blob/b155014ead6dbfc5687bf6808549fedd2d300316/server/main.js#L13-L17

Copy the permalink (on github web interface):
<img width="1006" alt="screen shot 2018-03-11 at 10 51 17 pm" src="https://user-images.githubusercontent.com/8143945/37254866-e90aa0ec-257e-11e8-9e6b-4e6aefb3b866.png">

Change the line numbers to capture all the code:
<img width="792" alt="screen shot 2018-03-11 at 10 51 42 pm" src="https://user-images.githubusercontent.com/8143945/37254870-12e4c9c4-257f-11e8-8282-e9eacdbf1a6c.png">

**Comment by anbud** [comment]
It was a simple error, but it was a little bit difficult to spot. 
`Applogs` had a lowercase `l` in the export command in `/imports/api/indexDB`, so importing `AppLogs` from there produced an undefined variable. Fixing it was just replacing `Applogs` with `AppLogs`.
Since it's a small fix, I've sent a PR in #497.

**Comment by gazhayes** [comment]
@anbud Do we need the ostrioLoggerMongo collection or is everything going into applogs?

**Comment by anbud** [comment]
@gazhayes, everything is going to `AppLogs`.
