### ISSUE TITLE
Problem: compare currencies doesn't link to currencies

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#525]
Problem: compare currencies doesn't link to currencies selected.

Solution: an icon left of name linking to currency.

**Comment by janat08** [comment]
doing this.

**Comment by janat08** [comment]
or I could style currency names as links (with on hover class), but then delete button would be uncomfortably close.

**Comment by gazhayes** [comment]
The icon thing is probably better, and if we can find the right icon it would also indicate that you are leaving that page.

**Comment by janat08** [comment]
i could open in new tab

**Comment by gazhayes** [comment]
Nah too annoying, users should control when they want a new tab or not (right click => open in new tab).

**Comment by MadanBhandari** [comment]
I have two points for Compare Currency page

1. Instead of having blank compare currency page, we could use add to compare (much like add to cart) button on currency details page or on home page itself. And also we need to set maximum currencies to be compared, otherwise user can select as many as s/he wanted, which eventually becomes unreadable and breaks UI as well.

[Reference](https://www.flipkart.com/mobiles/samsung~brand/pr?count=40&p%5B%5D=sort%3Drecency_desc&sid=tyy%2F4io&wid=1.productCard.PMU_V2) :
![compare-reference](https://user-images.githubusercontent.com/6429311/37300517-2b8de32a-264c-11e8-938d-b8762869059d.png)


2. We should update URL on campare as well like `/compare/BTC-ETH-LTC`, by this user can directly share compare results. No need to go to compare and select one by one, this will became too much when we added many currencies. [ NOT SURE IF THIS IS SAME #523 ]

**Comment by gazhayes** [comment]
Both good ideas. 

1. is a low priority thing at the moment, maybe we'll do it later. Another thing is users are going to want to bookmark or save currencies, we can put these currencies at the top of the list or something on the compare page.

2. is quite valuable, I'm going to log an issue for that.

**Comment by janat08** [comment]
installed fontawesome with async script.

**Comment by gazhayes** [comment]
It was already installed, so you changed from blocking/synchronous to async import right?

**Comment by janat08** [comment]
uninstalled fontawesome, used fortawesome package already installed.
