### ISSUE TITLE
problem: currencies sorted by auction ranking

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#534]
Problem: currencies that have been beaten in the auction remain high up on the list of currencies. They should resume their normal position rather than staying high up on the list for free.

**Comment by gazhayes** [comment]
later we'll probably sort by razor rank (doesn't exist yet) but for now may as well use _id since it's already indexed.

**Comment by anbud** [comment]
@gazhayes, it's currently sorted by `createdAt` field, like it was before. This sorting by auction ranking was due to the fact that `featured` field was undefined for most currencies. I've just fixed it on production by updating the database, so it should continue to sort by `createdAt`. Should I change the sort parameter to sort by `_id`?

**Comment by gazhayes** [comment]
Oh ok, no that's fine. We'll play around with sorting later, I just wanted to get the auction part working nicely.
