### ISSUE TITLE
problem: currency logo images are broken

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#575]

**Comment by AshHimself** [comment]
@gazhayes - I believe this is because coins are now referencing a thumbnail link instead of the orignal image. I just created a new coin then and it looked to work. 

This raises another issue. Changing coin images is no longer possible, I created this functionality before but the old changecurrencies page has been decommissioned.

**Comment by gazhayes** [comment]
> Changing coin images is no longer possible, I created this functionality before but the old changecurrencies page has been decommissioned.

#585

**Comment by gazhayes** [comment]
>  I believe this is because coins are now referencing a thumbnail link instead of the orignal image. I just created a new coin then and it looked to work.

OK. Is there more than 30 minutes of work to make existing images work? If not it's probably worth doing

**Comment by AshHimself** [comment]
I can download all the images that exist now, rename them with filename_thumbnail and then if you can upload them again that should fix it.

**Comment by gazhayes** [comment]
Oh that's all that's necessary? I'll just rename them on the server

**Comment by AshHimself** [comment]
You’ll need to make copies though... or the larger images won’t open in
modals if needed.

**Comment by AshHimself** [comment]
@gazhayes you could also actually just propose changes to the images you want to add now and approve them.

**Comment by AshHimself** [comment]
@gazhayes  - tested and just changed https://blockrazor.org/currency/monero
