### ISSUE TITLE
problem: [/problem] images cannot be expanded

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#651]
Problem: images cannot be expanded

solution: use thumbnail + full sized modal, currently in use on currencydetail route.

ping @AshHimself

**Comment by anbud** [comment]
I've actually reused the same code Ash used on currency details, but it refused to work. It's probably just a small bug I've missed.

**Comment by AshHimself** [comment]
I'll sort her out :)

**Comment by AshHimself** [comment]
Fixed in #674 

@anbud bit of troubleshooting on this yesterday and today and I learned something new. Having the modal ID "2322323asdfasdfasdf.jpeg"would not work, but "2322323asdfasdfasdf" would. Looks like jQuery modals do not [support](http://api.jquery.com/category/selectors/) fullstops when doing a lookup. I could of escaped it per the above documentation but I just removed it entirely.
