### ISSUE TITLE
Problem: Proof of Stake category doesn't have a sub-category list of PoS algos available (Site wide problem not just Currency page.)

### ISSUE THREAD

**Issue by sjmackenzie** [Blockrazor/blockrazor#680]
### Steps to reproduce:
* click on Cardano on the home page
* click to edit the "Hash Algorithm"

### Expected behaviour
* a drop down list of different algorithms appears, allowing the selection of PoS algos including `Ouroboros` (soon to be called `Ouroboros Praos`), the PoS used by Cardano.

### Actual behaviour
* the value `7be44dviDMiuoShan` appears

**Comment by gazhayes** [comment]
This problem runs deeper.

There actually shouldn't be a hash algorithm dropdown because Cardano uses proof of stake.

**Comment by sjmackenzie** [comment]
It uses Ouroboros

**Comment by gazhayes** [comment]
Ah yes, we should probably distinguish between different types of proof of stake. 

So the problem here is actually that proof of stake (on Blockrazor) doesn't allow sub-catagories like proof of work does.

**Comment by sjmackenzie** [comment]
Here's a short list of PoS algorithms
* Algorand
* Snow White
* Ouroboros
* Ouroboros Praos
...

**Comment by gazhayes** [comment]
It should be noted that:

1. the sub categories for proof of stake and proof of work are different,
2. this is a site-wide issue, not just the currency detail page. It needs to also be addressed on the add currency page.
3. Since new proof of stake and proof of work algorithms appear very often, we should allow users to create new proof of stake and proof of work sub-items (algorithms). This is currently implemented on the /hashpower route for proof of work but nowhere else.

**Comment by anbud** [comment]
I'm taking this one.

**Comment by anbud** [comment]
Done in #731.

**Comment by gazhayes** [comment]
The currency detail page also needs something like this.

**Comment by anbud** [comment]
I'll add it right away.

**Comment by anbud** [comment]
Done in #742.
