### ISSUE TITLE
problem: detecting lazy answering on rating questions isn't robust enough

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#712]
Problem: detecting lazy answering on rating questions isn't robust enough, users can click through mindlessly and earn krazor without reading the text. There's the ability to add 'checksum' questions already, however nothing is done about the speed of answering.

Solution: if the time between 2 answers is less than x seconds (I guess 5 seconds), trigger the lazy answering reset (this code already exists to deal with invalid checksum answers).

**Comment by samuelralak** [comment]
Hey @gazhayes I would like to handle this issue but am not sure how I can get to this page. Tried going through /ratings but things seem to be unresponsive here 😅am pretty sure am doing something wrong (sent you an email on this). Please advisde

**Comment by anbud** [comment]
@samuelralak, I'll give you an example.
This should be implemented on `/ratings`, `/communities` and `/codebase`. So, for example, go to `/communities`, add a few communities for cryptocurrencies and click next. Then, start answering questions. If your answer is 'tie' more than 10 times, or if you answer a checksum question incorrectly two times, it'll reset your progress and take away the rewarded bounty. The easiest way to test it is to just click 'tie' until it reacts.
The point of this issue is that we still do not check whether the user has actually read the question (which should take some time, about 5 seconds as @gazhayes stated) and that should be implemented.

You can see the current handling logic for communities [here](https://github.com/Blockrazor/blockrazor/blob/master/imports/ui/pages/communities/communities.js#L86-L114). The same code is also used for `/ratings` and `/codebase`.

**Comment by samuelralak** [comment]
@anbud quick question, is there any other way of adding community (besides from the `/addCoin`)?. I keep on being prompted to add a community but the only way I can see is through adding a new currency. Can't I select currencies with already existing communities?

**Comment by anbud** [comment]
@samuelralak, currently no, you can only add communities to currencies where you haven't added communities before. You can try this at `/ratings` and `/codebase`, the same principle applies, or create some random currencies for testing.

**Comment by samuelralak** [comment]
@anbud ok cool. trying that

**Comment by gazhayes** [comment]
There should be enough currencies there already to test with. You just need to add a wallet image whatever to pass the validation, it will the populate your questions.

**Comment by samuelralak** [comment]
@gazhayes the Next button `/ratings` seems to be unresponsive; getting the following error in develop:
<img width="817" alt="screen shot 2018-03-22 at 11 02 09 pm" src="https://user-images.githubusercontent.com/4476552/37795286-1f4f1dbe-2e25-11e8-8432-9853ccacb262.png">
Fixing that in my development environment seems to make it responsive again. please confirm whether you getting the same issue.

**Comment by gazhayes** [comment]
I'll have a look, but FYI you can check for these errors on the production server by going to /static/log.txt

**Comment by gazhayes** [comment]
Filed a new issue under #722

**Comment by samuelralak** [comment]
@gazhayes great. thanks

**Comment by gazhayes** [comment]
OK let's try an experiment. The necessary data point is knowing whether or not a task is being worked on, not who's working on it. I've created the "in progress" label. So now people can claim tasks with a comment and apply the in progress label.

**Comment by samuelralak** [comment]
@gazhayes one problem, I don't have permissions to add labels to issues. I'll just go ahead and comment on issues that am working on, then anyone with the right permissions could add the label.

**Comment by gazhayes** [comment]
How about now?

**Comment by samuelralak** [comment]
fixed in [#729](https://github.com/Blockrazor/blockrazor/pull/729). setting time difference between 2 answers to `5 seconds`
