### ISSUE TITLE
Problem: [/communities] communities page UX not good

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/blockrazor#716]
Problem: The communities page isn't styled and doesn't look very good.

Solution: apply same styling used in `/ratings` to `/communities` since these two pages have similar features.

**Comment by anbud** [comment]
@samuelralak, yap, this should be also done for `/codebase` as it's using the same unstyled template.

**Comment by samuelralak** [comment]
@anbud right, just noticed the same for `/codebase` as well. will fix this one.

**Comment by janat08** [comment]
would be great if a template were to be reused.

**Comment by AshHimself** [comment]
Are you working on this @samuelralak, do you have permissions to self assign issues to yourself so we all know what tickets are assigned to you?

**Comment by samuelralak** [comment]
@AshHimself no I don't have permissions to self assign issues to myself sadly. yes am working on this

**Comment by AshHimself** [comment]
I'm looking for some tickets to knock off, could you comment on which ones your doing and I can assign you mate?

**Comment by gazhayes** [comment]
Strictly speaking, we shouldn't use assignments because we run the risk of it devolving into maintainers assigning tasks to other people (which is not compatible with the C4). We should really just be using comments to say what we're taking. 

But assignments do make it much easier to see at a glance which issues are not being worked on, which is how I'm currently using them, we just need to be careful in making sure that the culture stays that way and doesn't devolve into assigning issues like a boss assigning tasks.

**Comment by AshHimself** [comment]
Right.. it makes sense to say you are taking this to comply with C4 but also makes sense to manage at a high level which tasks are free for the taking without opening each task one by one. Like everything.. pros and cons :)

**Comment by samuelralak** [comment]
@AshHimself ok cool.  I intend on picking up [#711](https://github.com/Blockrazor/blockrazor/issues/711) and [#712](https://github.com/Blockrazor/blockrazor/issues/712) after submitting a pull request for this one.

**Comment by samuelralak** [comment]
fixed in [#725](https://github.com/Blockrazor/blockrazor/pull/725)
