### ISSUE TITLE
problem: new curency bounty does not reset until new currency approved

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#718]
Problem: at present, the add currency bounty is reset upon approval of a new currency.

This is going to lead to a situation where the bounty keeps climbing while people add heaps of currencies, then it's going to reset a bunch of times as a maintainer (moderator) merges (approves) these new currencies. 

Possible solution: it's probably better to reset the bounty whenever someone submits a new currency instead of when that new currency is actually approved. 

I don't know though. Doing it this way would perhaps require some extra action or warnings on the addcoin page to reduce the ratio of correct vs incorrect currency additions. Maybe someone has some other ideas.

**Comment by anbud** [comment]
Changing when the bounty is reset is an easy fix (requires just changing a few lines), but I'm not sure about what's the smartest solution to this one. I agree, currently, bounty values can go quite high, but, if we reset the bounty when the currency is added (not approved) it could lead to constant small bounty values and users could spam incorrect new currencies just to lower the bounty.

When I implemented this one, my idea was that moderators would act quickly enough (as we would have many moderators), quicker than users adding new currencies, so that this shouldn't cause issues. Then again, I'm not sure if that would be feasible in early stages.

**Comment by gazhayes** [comment]
OK. I think we should just reset it upon submission. 

We can work out some extra steps later to make sure the submissions are generally correct and can't be fooled.

**Comment by anbud** [comment]
I'll take it.

**Comment by anbud** [comment]
Done in #728.
