### ISSUE TITLE
problem: [/wallet] scientific notation sometimes used for amounts

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#814]
Problem: scientific notation is used for amounts, this looks strange.

Krazor has a minimum atomic value of 0.00000000001 so we should probably take that into consideration in the UI. I'm not sure of the best solution though.

One possibility might be to somehow group transactions of the same type into something at the top of the wallet and simply display the total for each transaction type. This wouldn't need anywhere near as much precision (maybe 5 significant numbers). This could be followed by the huge table of all individual transactions with precision down to 0.00000000001

We could also remove the amount from the text of the message contained in each transaction item to make it shorter, this is not really needed now that we have the amounts in a separate column.

**Comment by samuelralak** [comment]
The transactions in the wallet are also not ordered. I would suggest that we should order the chronologically from the recent transactions to the oldest one

**Comment by samuelralak** [comment]
@gazhayes since we already know that the Krazor minimum atomic value has a max precision of 11, I have been able to convert the scientific notation numbers in amount to their actual values by using the solution [here](https://stackoverflow.com/a/36028587/2443926) with the [Number.prototype.toFixed()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) method.

For the messages, I have also been able to extract the krazor scientific amount in the message string and replacing it wih a non scientific value by applying the solution above. it works pretty well so far.  My reference for this were [this SO answer here](https://stackoverflow.com/a/658662/2443926) and the [String.replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_function_as_a_parameter) method.

**Comment by gazhayes** [comment]
We should stop using numbers in the message anyway since we have a value column anyway. 

Sorting deserves its own issue probably.

The numbers are being stored correctly right? This is only a UI issue?

**Comment by samuelralak** [comment]
Nop, its not just a UI problem. Thats how the numbers are being stored in
the database as well.

**Comment by gazhayes** [comment]
OK. That's the part to solve then. Existing transactions dont matter, only new ones.

**Comment by samuelralak** [comment]
ok cool. will take this one

**Comment by samuelralak** [comment]
this issue can be closed if there no more requirements
