### ISSUE TITLE
problem: [/rankings] Exception while invoking method 'answerRating' TypeError: Cannot read property 'xors' of undefined

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#850]
Problem: 
```
[34mI20180330-21:17:32.368(-4)? [39mException while invoking method 'answerRating' TypeError: Cannot read property 'xors' of undefined
[34mI20180330-21:17:32.369(-4)? [39m    at DDPCommon.MethodInvocation.answerRating (imports/api/ratings/server/methods.js:24:17)
```

**Comment by AshHimself** [comment]
Could you give more replication steps? I can't replicate.

**Comment by mstanuch** [comment]
Problematic method is `anwserRating` (file: `/imports/api/ratings/server/methods.js`).

I see two potential problems:
1. Missing `questionId` field  in `rating`, see code:
```js
// commit: 2684d71d5679b40725e054c414a572c89059bc3e
// lines: 20-24
let question = RatingsTemplates.findOne({ // ISSUE: missing document with id equal questionId
    _id: rating.questionId // ISSUE: rating.questionId=undefined
})
// HERE: missing check if `question` exist
if (question.xors) {
```
If field `questionId` in `rating` doesn't exists, then it will evaluates to `_id: undefined`. 
You don't have document with id `undefined` in your database, because of that `question` is evaluated to `undefined` ([Mongo.Collection#findOne](https://docs.meteor.com/api/collections.html#Mongo-Collection-findOne)). 
2. `rating.questionId` exists, but document doesn't exists.

**Proposed solution:**
Add missing validation and schemas (see also #272)

**Temporary solution (only development env)**
Try to cleanup your database.

**Comment by gazhayes** [comment]
@mstanuch thanks! I don't suppose you feel like sending a pull request?

**Comment by mstanuch** [comment]
Unfortunately I don't have access to computer with dev environment until Monday. Fell free to create PR if you want :)

**Comment by samuelralak** [comment]
pushing commit checking whether question is defined/exists

**Comment by samuelralak** [comment]
@gazhayes please confirm if this error persists after [#932](https://github.com/Blockrazor/blockrazor/pull/932) is merged

**Comment by gazhayes** [comment]
Appears to be fixed!
