### ISSUE TITLE
Problem: [/currency/x] Wallet image modal has invalid align

### ISSUE THREAD

**Issue by kevingilliard** [Blockrazor/blockrazor#938]
Problem: When user click the thumbnail for Wallet images in [/currency/x] page, the modal dialog appears.  But it's not center aligned and the image can be out of modal dialog area.
![image](https://user-images.githubusercontent.com/13878119/38345617-185b31ee-385e-11e8-90c1-7e20341d2e55.png)

Solution: Place modal dialog to horizontal center of window.  And if the image width is larger than modal dialog width, make image smaller to fit width.

**Comment by kevingilliard** [comment]
Ok, @gazhayes 
Thank you for your advice.
From now on, I'll log the issues first.  And if you say it's important, I'll start work on it.
It's a beginning to me on this project, so sometimes I forget the rules.

**Comment by gazhayes** [comment]
Don't worry, there's a learning curve, you're progressing nicely :)

Just to be clear, in this particular issue there was no problem with you starting work on it immediately (next time just make a comment that you are taking it first). I'm just slowly giving you this kind of information so that you take the right approach when things get more complicated.

**Comment by gazhayes** [comment]
Ah also @kevingilliard whoever opens an issue should close it when they are satisfied with the result.

Sometimes you solve your own issues, or sometimes someone else does, but whoever opened it is always the one to close it.
