### ISSUE TITLE
Problem: variety of currency codes used instead of KZR

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#953]
Problem: throughout Blockrazor there are a variety of currency codes used instead of KZR. This stems from the early days before a name was chosen. As an example, the wallet is using ZRQ instead of KZR.

**Comment by chamidu-supeshala** [comment]
Yes in the DB also there were three kinds of codes ZZR, KZR and ZRQ. So do we need to update the DB entries or  just change the application code to display all of above three codes as KZR ?

**Comment by chamidu-supeshala** [comment]
I mean the messages having codes like ZZR, ZRQ (generated by previous versions of Blockrazor)  still  available in the DB.

We can change the application code to generate new messages only with 'KZR', however this doesn't affect already generated messages with ZZR/ZRQ which are in the DB. 

For example, if we look at wallet transaction history of an old profile, we can see messages containing ZZR and ZRQ.

My problem is whether we need to refactor the DB by changing all the previously generated messages to use KZR label instead of ZZR/ZRQ      or        keep the old DB messages as it is and doing some application wise markup to convert old messages having the labels such as ZZR/ZRQ  to KZR label.

**Comment by gazhayes** [comment]
> I mean the messages having codes like ZZR, ZRQ (generated by previous versions of Blockrazor) still available in the DB.

OK that's what I thought too. That's fine, since that data will end up being purged later anyway.

**Comment by chamidu-supeshala** [comment]
fixed in #958

**Comment by gazhayes** [comment]
There's still ZRQ in the sidebar (small screens) and the top navbar.

**Comment by chamidu-supeshala** [comment]
Oh!  i'm very much sorry, forgot to refactor them in side/nav bars. i will correct them and resubmit a PR.

**Comment by chamidu-supeshala** [comment]
fixed them in #953 and again sorry for the inconvenience

**Comment by gazhayes** [comment]
No inconvenience! It's pretty easy to miss things at least sometimes ;)
